default_players = {
    'hungergames': [
        ("Bot1"),
        ("Bot2"),
        ("Bot3"),
        ("Bot4"),
        ("Bot5"),
        ("Bot6"),
        ("Bot7"),
        ("Bot8"),
        ("Bot9"),
        ("Bot10"),
        ("Bot11"),
        ("Bot12"),
        ("Bot13"),
        ("Bot14"),
        ("Bot15"),
        ("Bot16"),
        ("Bot17"),
        ("Bot18"),
        ("Bot19"),
        ("Bot20"),
        ("Bot21"),
        ("Bot22"),
        ("Bot23"),
        ("Bot24"),
    ]
}
